# server/docker-compose.yml

version: '3.8'

services:
  # Backend API Service
  api:
    build: .
    container_name: synergysphere-api
    ports:
      - "5001:5001"
    environment:
      - NODE_ENV=development
      - PORT=5001
      - MONGO_URI=mongodb+srv://swaminarayan2181_db_user:DpSPfatQWZz0sOLu@cluster0.9nqppzk.mongodb.net/synergysphere # Connects to the mongo service below
      - CORS_ORIGIN=http://localhost:3000
      - JWT_ACCESS_SECRET=51994cc5093422a79552ba25ecc3ec874f0f2806dbecac56cd784c43f73a8c4f
      - JWT_REFRESH_SECRET=0e1178801bcd45259b814009a5f9b9b8
      - JWT_ACCESS_EXPIRATION=15m
      - JWT_REFRESH_EXPIRATION=7d
      # Add other env vars here
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules # Prevents local node_modules from overwriting container's
    depends_on:
      - mongo
    command: npm run dev # Use dev script for live reloading

  # MongoDB Service
  mongo:
    image: mongo:latest
    container_name: synergysphere-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: always

volumes:
  mongo-data: