# server/docker-compose.yml
version: '3.8'

services:
  # Backend API Service
  api:
    build: .
    container_name: synergysphere-api
    ports:
      - "5001:5001"
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules # Prevents local node_modules from overwriting container's
    depends_on:
      - mongo
    command: npm run dev

  # MongoDB Service
  mongo:
    image: mongo:latest
    container_name: synergysphere-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_DB_NAME}

volumes:
  mongo-data: